app:
  title: OBOS
  baseUrl: http://localhost:3000

organization:
  name: OBOS

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      apps:
        - appId: ${APP_GITHUB_APP_ID}
          clientId: ${APP_GITHUB_CLIENT_ID}
          clientSecret: ${APP_GITHUB_CLIENT_SECRET}
          webhookUrl: ${APP_GITHUB_WEBHOOK_URL}
          webhookSecret: ${APP_GITHUB_WEBHOOK_SECRET}
          privateKey: ${APP_GITHUB_PRIVATE_KEY}

proxy:
  ###

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

#enableExperimentalRedirectFlow: true

auth:
  # environment: development
  providers:
    github:
      development:
        clientId: ${OAUTH_GITHUB_CLIENT_ID}
        clientSecret: ${OAUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolver
            # emailMatchingUserEntityProfileEmail usernameMatchingUserEntityName
            - resolver: usernameMatchingUserEntityName

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  rules:
    - allow: [Component, API, Domain, System, Resource] # Restrict entity types (default)
  providers:
    # Github catalog entity data. See https://backstage.io/docs/integrations/github/discovery/
    github:
      commonRepo: # ProviderId
        organization: 'aparteas'
        catalogPath: '/*.yaml'
        rules:
          allow: [Domain, System, Resource] # Restrict entity types
        filters:
          repository: 'blueprint-catalog'
          visibility: # Search in both public and private repos
            - public
            - internal
        schedule:
          initialDelay: { seconds: 5 }
          frequency: { hours: 1 }
          timeout: { seconds: 30 }
      devRepos: # ProviderId
        organization: 'aparteas'
        catalogPath: '/catalog-info.yaml'
        rules:
          allow: [Component, API, Resource] # Restrict entity types
        filters:
          visibility: # Search in both public and private repos
            - public
            - internal
        schedule:
          initialDelay: { seconds: 5 }
          frequency: { hours: 1 }
          timeout: { seconds: 30 }

    # Github org data. See https://backstage.io/docs/integrations/github/org
    githubOrg:
      - id: github
        githubUrl: https://github.com
        orgs: ['aparteas']
        schedule:
          initialDelay: { seconds: 5 }
          frequency: { hours: 1 }
          timeout: { seconds: 30 }
  # Experimental: Always use the search method in UrlReaderProcessor.
  # New adopters are encouraged to enable it as this behavior will be the default in a future release.
  useUrlReadersSearch: true

#kubernetes:
# see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true
