apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blueprint
  title: Blueprint
  description: OBOS Developer Portal (Backstage)
  tags:
    - node
    - backstage
spec:
  type: website
  owner: team-dx
  system: system-blueprint
  lifecycle: experimental
  dependsOn:
    - resource:default/runtime-dx-aks
    - component:default/blueprint-catalog
