site_name: ${{values.component_id}}
site_description: ${{values.description}}

nav:
  - Home: index.md
  - About:
      - Overview: about/overview.md
      - Team: about/team.md
  - Documentation:
      - Getting Started: getting_started.md
      - User Guide:
          - Installation: user_guide/installation.md
          - Configuration: user_guide/configuration.md
theme:
  name: readthedocs

